name: "Bundle Size check @excalidraw/excalidraw"
on:
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install
      - name: Build package
        run: yarn build:package
      - name: List build output
        run: ls -R packages/excalidraw/dist
      - name: Run size-limit
        run: npx size-limit --json
